### PR TITLE
Fix Event Names

### PR DESCRIPTION
**Pull request by AnatoleAM**
The default listeners outlined in the [`EventSource`](https://developer.mozilla.org/en-US/docs/Web/API/EventSource) Web API are `open` and `message`. This changes the "update" event to "message". "connected" was also changed to "listening", as it sounds redundant with the default-fired `open` event, whereas `listening` indicates the connection is fully ready to receive events.

### CODE REVIEW

**Comment by TroyDota** [comment]
Wtf is this?

**Comment by TroyDota** [comment]
The default listeners are not. Open and message, those are both client side afaik. Open is when the connection is opened and message is all messages.

**Comment by TroyDota** [comment]
Why are you changing the payload structure?

**Comment by AnatoleAM** [comment]
> The default listeners are not. Open and message, those are both client side afaik. Open is when the connection is opened and message is all messages.

I changed back `open` (now `listening`) after discovering the browser fires it autonomously. Also, since the URL itself indicates the type of data the client expects, there's no need to specify it

**Comment by AnatoleAM** [comment]
> Why are you changing the payload structure?

So that it's in line with 7TV semantics. It was also missing emote data

**Comment by TroyDota** [comment]
What? Do u mean the update event?

**Review by TroyDota — APPROVED** [review]

**Comment by TroyDota** [comment]
👍

**Pull request merged**
